# Configuration for the `privx-secrets' utility program.

[api]

endpoint = 'https://localhost:8443'
certificate = '''
-----BEGIN CERTIFICATE-----
MIIFbzCCA1egAwIBAgIIOChF+MxDEPYwDQYJKoZIhvcNAQELBQAwJzEVMBMGA1UE
...
kl63kE0WRSqUcp1gz4YD7ZwU+hvR2x20LojBZ9NFc0tRP3ZAaHc3XaZX5i2sakSI
+X/uf2c5HQOdQejXGBSLSG9RgvKCQwMPEBQnMxoXI43WgIrOKQaAs9x/3qRvBwLs
s8qr
-----END CERTIFICATE-----
'''

[auth]
oauth_client_id 	= "privx-ui"
#oauth_client_secret	= "XXX"
oauth_redirect_uri	= "/oauth-callback"
api_client_id		= "Local User Accessing Secrets"
api_client_secret	= "password for Local User"
